package com.customwars.client.ui.state.input;

public enum CommandEnum {
  SELECT, CANCEL, EXIT,
  DOWN, UP, LEFT, RIGHT,
  TOGGLE_MUSIC, ZOOM_IN, ZOOM_OUT, FILL_MAP,
  NEXT_PAGE, PREV_PAGE, RECOLOR, DELETE, END_TURN,
  TOGGLE_CONSOLE, TOGGLE_FPS, TOGGLE_EVENT_VIEWER,
  SAVE, OPEN, NEW, UNIT_CYCLE
}
